### ISSUE TITLE
Unable to compile ASP.NET Core app

### ISSUE THREAD

**Issue by chankai420** [ScarletKuro/nadeko-dotnetcore-buildpack#1]
When deploying app on Heroku using this buildpack, the process would go on normally until the app is to be compiles, after which it wold fail to do so. Is there any way to fix this issue? I have tried using your version of NadekoBot and other programmes.
![issue](https://user-images.githubusercontent.com/27469998/40719937-b4495ba2-6447-11e8-913e-1e2586dd2690.JPG)

**Comment by ScarletKuro** [comment]
@chankai420 
Oh, after such long time I just noticed the issue on github. This buildpack was intended for old NadekoBot, so I can't guarantee work of ASP,net or any other application.
Also, it's using 1.0.0-preview2-1-003177, which is very old and doubt that it's being used anywhere, I guess your ASP.Net application is using newer versions, which make the compile to fail. I have buildpack v2.1 which is more universal and using fresh dotnet, the only disadvantage of the buildpack is that i missed to add
`export PATH="/app/.heroku/dotnet:${PATH}"` thatch why you should add it yourself to make `dotnet` command available globally.
